name: friendo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  hexcolor: ^3.0.1
  shared_preferences: ^2.2.3
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  logging: ^1.2.0
  sqflite: ^2.3.3+1
  http: ^1.2.1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  firebase_messaging: ^14.9.1
  curved_labeled_navigation_bar: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
          weight: 700
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
