// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabJTupc1EAQkponPCdJbsASGjdWwlFgI',
    appId: '1:572523836299:web:0a7e19e79fc9100d1f358e',
    messagingSenderId: '572523836299',
    projectId: 'friendo-14343',
    authDomain: 'friendo-14343.firebaseapp.com',
    storageBucket: 'friendo-14343.appspot.com',
    measurementId: 'G-VF7WV798MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpO5f9Tlelvt1CUIMM1fN773sj_P2Kl8',
    appId: '1:572523836299:android:cbb30f3c83ab31711f358e',
    messagingSenderId: '572523836299',
    projectId: 'friendo-14343',
    storageBucket: 'friendo-14343.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCabJTupc1EAQkponPCdJbsASGjdWwlFgI',
    appId: '1:572523836299:web:784e2b4a92e433a81f358e',
    messagingSenderId: '572523836299',
    projectId: 'friendo-14343',
    authDomain: 'friendo-14343.firebaseapp.com',
    storageBucket: 'friendo-14343.appspot.com',
    measurementId: 'G-BB9KPQF0H8',
  );
}
